kind: Service
apiVersion: v1
metadata:
  name: modernportal-service # Service name
spec:
  type: LoadBalancer
  selector:
    env: modernportal # Label selector. The Service targets Pods that use this label
  ports:
  - port: 3001 # Port used to access the Service from within the cluster.
    targetPort: 3000 # Port opened by targeted Pods
