kind: Service
apiVersion: v1
metadata:
  name: legacyportal-service # Service name
spec:
  type: LoadBalancer
  selector:
    env: legacyportal # Label selector. The Service targets Pods that use this label
  ports:
  - port: 80 # Port used to access the Service from within the cluster.
    targetPort: 3000 # Port opened by targeted Pods
