apiVersion: v1
kind: Pod
metadata:
    name: insurance-data-service
    labels:
      env: insurance-data-service
spec:
  containers:
  - name: insurance-data-service
    image: felixreichenbach/insurance-data-service:latest
    env:
    - name: SPRING_DATA_MONGODB_URI
      value: mongodb+srv://user:password@sandbox-afb5d.mongodb.net/test?retryWrites=true
    - name: SPRING_DATA_MONGODB_DATABASE
      value: insurance
