apiVersion: v1
kind: Pod
metadata:
    name: mainframe-simulator
    labels:
      env: mainframe-simulator
spec:
  containers:
  - name: mainframe-simulator
    image: felixreichenbach/mainframe-simulator:latest
    env:
    - name: SPRING_DATA_MONGODB_URI
      value: mongodb+srv://user:password@sandbox-afb5d.mongodb.net/test?retryWrites=true
    - name: SPRING_DATA_MONGODB_DATABASE
      value: insurance

