kind: Service
apiVersion: v1
metadata:
  name: mainframe-simulator-service # Service name
spec:
  type: LoadBalancer
  selector:
    env: mainframe-simulator # Label selector. The Service targets Pods that use this label
  ports:
  - port: 8080 # Port used to access the Service from within the cluster.
    targetPort: 8080 # Port opened by targeted Pods
